### PR TITLE
Add automation script to make things much simpler to setup.

### PR DESCRIPTION
**Pull request by ghost**
Hope this helps Spotlight, you might recognize the WAD repacking method from RC24's IOS Patcher actually.

### CODE REVIEW

**Comment by ghost** [comment]
By the way @spotlightishere, could you change the target branch to patch-4? That branch is similar, but I did it in less commits :)
It even has more features too.

**Comment by ghost** [comment]
But yeah, with this concept, there is more to come. I am going to use this patching framework I made to power the WiiLink24 UNIX patching engine.

**Comment by spotlightishere** [comment]
Hi, and thank you for your interest in my project.
This repository is meant for reverse-engineering oriented people as it alone isn't 100% useful for determining EC's responses or interaction. I have no interest in making it easily available to an end user as it serves zero use or gain to anyone asides utilising it beyond that purpose.

I'm not quite sure what you mean for patching here either - I thought in the end anything would be as easy as one script?

**Comment by ghost** [comment]
It will, but it sets up a patched WAD too :)

**Pull request closed without merging**
